### ISSUE TITLE
Change icons used for Aeronavics theming

### ISSUE THREAD

**Issue by edwinhayes** [Aeronavics/MissionPlanner#10]
The favicon and taskbar icon should change to Aeronavics themed ones: I think from memory maybe there is some reason why it's not easy to have them change automatically when the theme is changed at runtime, but we'll want this to be themed correctly for our customers regardless.

**Comment by JWangAeronavics** [comment]
commit ids: b5ef781857d1542dfb0a3ec409bcd4f24c1a8af8 b9f9a2c18fb5989fa023193cfa5cffdecf19ccfe
