### ISSUE TITLE
Abnormal behaviour of 'Testing Screen' button.

### ISSUE THREAD

**Issue by edwinhayes** [Aeronavics/MissionPlanner#13]
On Config/Tuning->Planner, at the bottom of the screen there is a checkbox for the 'Testing Screen'.  Changing the state of this control brings up the 'Secret Menu': selecting the box makes it appear, but deselecting the box makes the window vanish but instantly reappear, which is obviously insane.

**Comment by JWangAeronavics** [comment]
commit id: 15365ad311a94396c497bb5c8a08771802db4a71
