### ISSUE TITLE
Inconsistent theming on Flight Plan screen.

### ISSUE THREAD

**Issue by edwinhayes** [Aeronavics/MissionPlanner#14]
Still some burnt kermit here under Aeronavics theme.

**Comment by JWangAeronavics** [comment]
Theme manager is missing a few lines of code that modify the XPanderControls panel class (third party library for collapsing panels

**Comment by JWangAeronavics** [comment]
fixed by commit ID: 5eb2ca83640d78014b20840e7d3c6bf7dfd3e919
