### ISSUE TITLE
Increase the default telemetry rates

### ISSUE THREAD

**Issue by edwinhayes** [Aeronavics/MissionPlanner#18]
We normally have plenty of bandwidth, so we should make us of it to improve the fluidity of the UI updating in Mission Planner.  This can be done using the fields in the preferences screen, so all that is required here is to turn up the default values, after testing to determine that the selected rates are stable.

**Comment by JWangAeronavics** [comment]
increased attitude and sensor update rate to 8Hz and position update to 5Hz, tested against Large ground control station and was running stable. higher sensor and attitude updates cause buffering in the graphics updates and unstable behaviour.

commit id: eea76589b7ab2c601efb6cc0277a2ed126262c79
