### ISSUE TITLE
Remove turn/slip indicator from HUD

### ISSUE THREAD

**Issue by edwinhayes** [Aeronavics/MissionPlanner#20]
The turn/slip indicator, and a few other things on the HUD, are not really relevant for a multi-rotor, and should be controlled by layout/theme selection, as per other elements.

**Comment by edwinhayes** [comment]
Remove the turn/slip indicator.
Remove the time.
Update the "0>0" string to "0m > WP0" or something.

**Comment by JWangAeronavics** [comment]
commit id: bed7580f05728da3ac0a2cfc8f3ab333c2356990
