### ISSUE TITLE
Tab for control of payloads.

### ISSUE THREAD

**Issue by edwinhayes** [Aeronavics/MissionPlanner#22]
As discussed, some way of interacting with MAVLink gimbals.

At minimum, a slider to control the pitch angle.

Better if it also has some ability to report payload status.
Better if can link to the SD card contents when possible.
Better if can switch camera in/out of USB mode.  Might require firmware to match.
Better if the tab is only present if the payload is.  Might require firmware to match.

**Comment by JWangAeronavics** [comment]
commit ids: 184767223c6e5c02b26197bb4018298da2b3f0c4 184767223c6e5c02b26197bb4018298da2b3f0c4

Created a tab with sliders to control tilt, pan and roll using sliders with textboxes reporting the flightcontroller's mount pitch/roll/yaw positions. The tab automatically appears when a mavlink gimbal is detected and the current mav target is the flight controller and disappears for all other combinations.
Tab also includes a button that links to the payload directory of the MAV that is currently being connected to.

Reporting additional payload statuses (i.e. those from the payload controller or camera) and switching the camera in and out of USB mode will require further work.
