### ISSUE TITLE
Remove other aircraft types from simulator tab

### ISSUE THREAD

**Issue by edwinhayes** [Aeronavics/MissionPlanner#23]
Also, any other cursory changes which can be made to the simulator configuration (which I assume is basically all stored in a configuration file somewhere, but I suppose it could equally be some non-sane arrangement) to make the simulated aircraft more like a Navi.

**Comment by JWangAeronavics** [comment]
physical parameters of the simulation vehicles are compiled into the SITL files, any modification would require building and hosting the files ourselves

**Comment by JWangAeronavics** [comment]
commit id:6dfb7f02904deb1b8087e1700e0e32363437b9e7
