### ISSUE TITLE
Create separate basic and advanced Aeronavics layouts.

### ISSUE THREAD

**Issue by edwinhayes** [Aeronavics/MissionPlanner#6]
Create a list of the various screens/tabs/etc which are in Mission Planner and could potentially be maskable, and then arrange a meeting where we go through the list and tick whether or not each thing should be presented to the user in each of the basic/advanced modes.

The 'connection type' menu at top right isn't a screen in its own right, but is an good example.

**Comment by edwinhayes** [comment]
Actually, maybe there should be three layouts, because their might need to be a tier between non-technical customer, and Chris Jackson, in terms of what is exposed.

**Comment by JacksonUAS** [comment]
This sounds like an R&D Task

**Comment by edwinhayes** [comment]
Correct.  Why?

**Comment by JWangAeronavics** [comment]
Displayview changes have been merged from upstream, and customisations applied to define the 3 agreed upon modes. changes pushed to the aeronavics-dev branch
